name: flitter
description: A new flutter project.
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  intl: any
  http: any
  flutter_webview_plugin: any
  redux: any
  shared_preferences: any
  url_launcher: any
  gitter:
    git:
      url: "git@github.com:izambasiron/gitter_dart.git"
      ref: "update-faye"
  flutter_markdown: any
  flutter_color_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/html/success.html
    - assets/images/banner.jpg
